apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
- target:
    version: v1alpha1
    group: operators.coreos.com
    kind: Subscription
    name: openshift-pipelines-operator
    namespace: openshift-operators
  patch: |-
    - op: replace
      path: /spec/channel
      value: stable
