apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- operatorgroup.yaml
- catalogsource.yaml
- subscription.yaml
- namespace-gitea.yaml
- rolebinding.yaml
- gitea.yaml
