apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
- target:
    version: v1
    group: gpte.opentlc.com
    kind: Gitea
    name: gitea
  patch: |-
    - op: replace
      path: /spec/giteaRoute
      value: gitea.apps.ocp410-cnv.infra.demos.redhat.com