apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../cluster-config/authentication
- ../../../cluster-config/authorization
- ../../../operators/openshift-serverless
- ../../../operators/openshift-pipelines/overlays/dev
- ../../../operators/gitea/overlays/dev-410
- ../../../operators/quay
- ../../../operators/web-terminal

# - ../../../cluster-config/clusterversion/dev-410
# - ../../../operators/openshift-data-foundations
